// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      /*case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;*/
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDtKT5Dd-NOko6DCWgDFl6NqfJPCE8_4XQ",
      authDomain: "enreda-d3b41.firebaseapp.com",
      databaseURL: "https://enreda-d3b41.firebaseio.com",
      projectId: "enreda-d3b41",
      storageBucket: "enreda-d3b41.appspot.com",
      messagingSenderId: "791604879416",
      appId: "1:791604879416:web:e2c7ad6a51a4307ee086cd",
      measurementId: "G-J992Z19JRL"
  );

  /* TODO: Estas son las opciones para enreda-empresas, enredaentidadsocial no está para móviles ahora mismo en el proyecto Firebase
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlgBp23w5QCr2kQ40u2xcf9Vs-gocrZGI',
    appId: '1:791604879416:android:5340cb517d0e429fe086cd',
    messagingSenderId: '791604879416',
    projectId: 'enreda-d3b41',
    databaseURL: 'https://enreda-d3b41.firebaseio.com',
    storageBucket: 'enreda-d3b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhgFnypW2P9ce7KNVrrVkMknRuvniuD3o',
    appId: '1:791604879416:ios:d82f58a9aa1f437ae086cd',
    messagingSenderId: '791604879416',
    projectId: 'enreda-d3b41',
    databaseURL: 'https://enreda-d3b41.firebaseio.com',
    storageBucket: 'enreda-d3b41.appspot.com',
    androidClientId: '791604879416-4kgdq267i6qdutk56llo04qaf6igvq96.apps.googleusercontent.com',
    iosClientId: '791604879416-i92n2mjjo7nmgmjfrpflahse24ed6qsr.apps.googleusercontent.com',
    iosBundleId: 'org.sic4change.enredaEmpresas',
  );
   */
}
