import 'package:enreda_empresas/app/common_widgets/expanded_row.dart';
import 'package:enreda_empresas/app/utils/adaptative.dart';
import 'package:enreda_empresas/app/values/strings.dart';
import 'package:enreda_empresas/app/values/values.dart';
import 'package:flutter/material.dart';

Widget resourceRevisionForm(
    BuildContext context,
    String resourceTitle,
    String resourceDescription,
    String resourceTypeName,
    String resourceCategoryName,
    String selectedDegree,
    String selectedContract,
    String selectedSalary,
    String interestsNames,
    String formattedStartDate,
    String formattedEndDate,
    String formattedMaxDate,
    String duration,
    String schedule,
    String place,
    String capacity,
    String countryName,
    String provinceName,
    String cityName,
    String address,
    String promotor,
    String organizerText,
    String link,
    //bool trust,
    String phone,
    String email,
    String resourcePictureName
) {
  TextTheme textTheme = Theme.of(context).textTheme;
  double fontSize = responsiveSize(context, 14, 16, md: 15);
  return Column(
    children: [
      CustomExpandedRow(title: StringConst.FORM_TITLE, text: resourceTitle),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRowMultiline(title: StringConst.DESCRIPTION, text: resourceDescription),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_RESOURCE_TYPE, text: resourceTypeName),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_RESOURCE_CATEGORY, text: resourceCategoryName),
      (selectedDegree != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (selectedDegree != '') ? CustomExpandedRow(title: StringConst.FORM_DEGREE, text: selectedDegree) : Container(),
      (selectedContract != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (selectedContract != '') ? CustomExpandedRow(title: StringConst.FORM_CONTRACT, text: selectedContract) : Container(),
      (selectedSalary != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (selectedSalary != '') ? CustomExpandedRow(title: StringConst.FORM_SALARY, text: selectedSalary) : Container(),
      (formattedStartDate != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (formattedStartDate != '') ? CustomExpandedRow(title: StringConst.FORM_START, text: formattedStartDate) : Container(),
      (formattedEndDate != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (formattedEndDate != '') ? CustomExpandedRow(title: StringConst.FORM_END, text: formattedEndDate) : Container(),
      (formattedMaxDate != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (formattedMaxDate != '') ? CustomExpandedRow(title: StringConst.FORM_MAX, text: formattedMaxDate) : Container(),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_DURATION, text: duration),
      (schedule != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (schedule != '') ? CustomExpandedRow(title: StringConst.FORM_SCHEDULE, text: schedule) : Container(),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_PLACE, text: place),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_CAPACITY, text: capacity),
      (interestsNames != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (interestsNames != '') ? CustomExpandedRow(title: StringConst.FORM_INTERESTS, text: interestsNames) : Container(),
      (countryName != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (countryName != '') ? CustomExpandedRow(title: StringConst.FORM_COUNTRY, text: countryName) : Container(),
      (provinceName != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (provinceName != '') ? CustomExpandedRow(title: StringConst.FORM_PROVINCE, text: provinceName) : Container(),
      (cityName != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble):Container(),
      (cityName != '') ? CustomExpandedRow(title: StringConst.FORM_CITY, text: cityName):Container(),
      (address != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (address != '') ? CustomExpandedRow(title: StringConst.FORM_ADDRESS, text: address) : Container(),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_PROMOTOR, text: promotor),
      (organizerText != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (organizerText != '') ? CustomExpandedRow(title: StringConst.FORM_ORGANIZER_TEXT, text: organizerText) : Container(),
      (phone != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (phone != '') ? CustomExpandedRow(title: StringConst.FORM_PHONE, text: phone) : Container(),
      (email != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (email != '') ? CustomExpandedRow(title: StringConst.FORM_EMAIL, text: email) : Container(),
      (link != '') ? const SizedBox(height: Sizes.kDefaultPaddingDouble) : Container(),
      (link != '') ? CustomExpandedRow(title: StringConst.FORM_LINK, text: link) : Container(),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      CustomExpandedRow(title: StringConst.FORM_RESOURCE_PICTURE, text: resourcePictureName),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
      /*CustomExpandedRow(title: StringConst.FORM_TRUST, text: trust == true ? "Si" : "No"),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),*/
      Text(StringConst.FORM_ACCEPTANCE,
        style: textTheme.bodySmall?.copyWith(
          height: 1.5,
          color: AppColors.greyDark,
          fontWeight: FontWeight.w400,
          fontSize: fontSize,
        ),),
      const SizedBox(height: Sizes.kDefaultPaddingDouble),
    ],
  );
}